### ISSUE TITLE
AttributeError: module 'octis' has no attribute 'configuration'

### ISSUE THREAD

**Issue by rsreetech** [MIND-Lab/OCTIS#10]
* OCTIS version: 1.3.0
* Python version: 3.6
* Operating System: Windows

### Description
Tried to run the server and create an experiment

### What I Did
127.0.0.1 - - [27/Apr/2021 20:06:58] "[37mPOST /selectPath HTTP/1.1[0m" 200 -
{'partitioning': False, 'path': 'D:/OctisResults', 'dataset': '20NewsGroup', 'model': {'name': 'LDA', 'parameters': {'alpha': 0.1, 'eta': 0.1, 'iterations': 50, 'passes': 1}}, 'optimization': {'iterations': 5, 'model_runs': 3, 'surrogate_model': 'GP', 'n_random_starts': 3, 'acquisition_function': 'LCB', 'search_spaces': {'num_topics': {'low': 2, 'high': 20}}}, 'optimize_metrics': [{'name': 'Coherence', 'parameters': {'measure': 'c_npmi', 'texts': 'use dataset texts', 'topk': 10}}], 'track_metrics': [{'name': 'Coherence', 'parameters': {'measure': 'c_npmi', 'texts': 'use dataset texts', 'topk': 10}}]}
127.0.0.1 - - [27/Apr/2021 20:07:20] "[37mPOST /startExperiment HTTP/1.1[0m" 200 -
starting OctExpnewsgroup
Process Process-2:1:
Traceback (most recent call last):
  File "D:\octisExp\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\octisExp\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\octisExp\lib\site-packages\octis\dashboard\queueManager.py", line 260, in _execute_and_update
    startExperiment(toRun[running[0]])
  File "D:\octisExp\lib\site-packages\octis\dashboard\experimentManager.py", line 136, in startExperiment
    model_class = importModel(parameters["model"]["name"])
  File "D:\octisExp\lib\site-packages\octis\dashboard\experimentManager.py", line 64, in importModel
    model = importClass(model_name, model_name, module_path)
  File "D:\octisExp\lib\site-packages\octis\dashboard\experimentManager.py", line 46, in importClass
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\octisExp\lib\site-packages\octis\models\LDA.py", line 5, in <module>
    import octis.configuration.citations as citations
AttributeError: module 'octis' has no attribute 'configuration'

**Comment by pietrotrope** [comment]
Hello! thanks for reporting this error.
During the weekend I will try to work on it.

Best, 

Pietro

**Comment by pietrotrope** [comment]
Hi!
the issue should be solved.
Let me know!

Cheers,

Pietro
