### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Spartanlasergun** [MIND-Lab/OCTIS#123]
* OCTIS version: 1.13.1
* Python version: 3.12.3
* Operating System: Windows

### Description

Trying regular to install octis using a regular pip install commands and I keep getting an error that I think is related to a deprecated module.

### What I Did

```
pip install octis

Collecting gensim==4.2.0 (from octis==1.13.1)
  Using cached gensim-4.2.0.tar.gz (23.2 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: nltk in c:\users\bns36\appdata\local\programs\python\python312\lib\site-packages (from octis==1.13.1) (3.8.1)
Requirement already satisfied: pandas in c:\users\bns36\appdata\local\programs\python\python312\lib\site-packages (from octis==1.13.1) (2.1.4)
Requirement already satisfied: spacy in c:\users\bns36\appdata\local\programs\python\python312\lib\site-packages (from octis==1.13.1) (3.7.4)
Collecting scikit-learn==1.1.0 (from octis==1.13.1)
  Using cached scikit-learn-1.1.0.tar.gz (6.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\bns36\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\bns36\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bns36\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\bns36\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bns36\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\bns36\AppData\Local\Temp\pip-build-env-38b2a8n9\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\bns36\AppData\Local\Temp\pip-build-env-38b2a8n9\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\bns36\AppData\Local\Temp\pip-build-env-38b2a8n9\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by prikarsartam** [comment]
Hello there,

Downgrade to python version `<12` and it will be resolved. You may take a look at [link for a github issue](https://github.com/pypa/pip/issues/12179).

**Comment by Spartanlasergun** [comment]
> Hello there,
> 
> Downgrade to python version `<12` and it will be resolved. I am using it within a conda virtual environment with `Python3.10` in it and it works fine. You may take a look at [a link for the same issue in a different ](https://github.com/pypa/pip/issues/12179).
> 
> You may find a few more trouble after this which I have posted at #125 .
> 
> Hope it helps.

I did a manual install offline using the setup.py file after modifying the requirements and it worked, though some functions that I haven't tested may be broken. It needs to be updated though - serious roadblock for people working with topic modeling as OCTIS is mentioned in the seminal paper on BERTopic.

**Comment by prikarsartam** [comment]
> > Hello there,
> > Downgrade to python version `<12` and it will be resolved. I am using it within a conda virtual environment with `Python3.10` in it and it works fine. You may take a look at [a link for the same issue in a different ](https://github.com/pypa/pip/issues/12179).
> > You may find a few more trouble after this which I have posted at #125 .
> > Hope it helps.
> 
> I did a manual install offline using the setup.py file after modifying the requirements and it worked, though some functions that I haven't tested may be broken. It needs to be updated though - serious roadblock for people working with topic modeling as OCTIS is mentioned in the seminal paper on BERTopic.

Downgrading to relevant versions and updating the requirements.txt file here would suffice that.
