### ISSUE TITLE
ETM training fails.

### ISSUE THREAD

**Issue by cidrugHug8** [MIND-Lab/OCTIS#20]
* OCTIS version: 1.8.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04.02

### Description

ETM training fails.

### What I Did

```
dataset = Dataset()
dataset.load_custom_dataset_from_folder(DATASET_PATH)
model = ETM(num_topics=TOPIC_SIZE)
model_output = model.train_model(dataset)
save_model_output(model_output, MODEL_OUTPUT_PATH)
save_model_output(model, MODEL_PATH)
```
The following error message was displayed.
```
model: ETM(
  (t_drop): Dropout(p=0.5, inplace=False)
  (theta_act): ReLU()
  (rho): Linear(in_features=300, out_features=221413, bias=False)
  (alphas): Linear(in_features=300, out_features=25, bias=False)
  (q_theta): Sequential(
    (0): Linear(in_features=221413, out_features=800, bias=True)
    (1): ReLU()
    (2): Linear(in_features=800, out_features=800, bias=True)
    (3): ReLU()
  )
  (mu_q_theta): Linear(in_features=800, out_features=25, bias=True)
  (logsigma_q_theta): Linear(in_features=800, out_features=25, bias=True)
)
Traceback (most recent call last):
  File "train.py", line 62, in <module>
    model_output = model.train_model(dataset)
  File "/usr/local/lib/python3.8/dist-packages/octis/models/ETM.py", line 57, in train_model
    continue_training = self._train_epoch(epoch)
  File "/usr/local/lib/python3.8/dist-packages/octis/models/ETM.py", line 149, in _train_epoch
    data_batch = data.get_batch(self.train_tokens, self.train_counts, ind, len(self.vocab.keys()),
  File "/usr/local/lib/python3.8/dist-packages/octis/models/ETM_model/data.py", line 17, in get_batch
    doc = [doc.squeeze()]
AttributeError: 'list' object has no attribute 'squeeze'
```

**Comment by silviatti** [comment]
Hi, since you are having trouble with two models, I think the problem may be related to the dataset. Can you please make sure that the dataset is in the [correct format](https://github.com/MIND-Lab/OCTIS/blob/master/README.rst#load-a-custom-dataset)? Maybe there are some empty documents (this is probably something that we do not handle).

**Comment by cidrugHug8** [comment]
Thanks for the advice.
I'll check my data set.

**Comment by cidrugHug8** [comment]
My data set was formatted incorrectly. Thanks for the advice!
